### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by thoppe** [matthagy/PyLJFluid#1]
On a stock install of Ubuntu 12.10/numpy the installation

```
python setup.py build
sudo python setup.py install
```

works, but running the demo

```
python Demo/compute_gr.py
```

fails with

```
Traceback (most recent call last):
  File "Demo/compute_gr.py", line 4, in <module>
    from pyljfluid.components import (LJForceField, Config, MDSimulator,
  File "/usr/local/lib/python2.7/dist-packages/pyljfluid/__init__.py", line 29, in <module>
    from components import *
  File "/usr/local/lib/python2.7/dist-packages/pyljfluid/components.py", line 27, in <module>
    from base_components import (NeighborsTable, BaseForceField, LJForceField, BaseConfig,
ImportError: cannot import name BaseForceField
```

**Comment by jpetersen48** [comment]
Hopefully it isn't rude to comment on a multi-year old thread like this, but the problem is in a mislabelled variable in `pylfjluid/components.py`

To fix it, before running setup.py, you should go into `pyljfluid/components.py` and on lines 27 and 37, change `BaseForceField` to `BasePyForceField`. If you have already run the setup, the same fix will work, just be sure to go to `/lib/python2.7/site-packages/pyljfluid/components.py` and make the change there.
